apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: custom-csi
spec:
  selector:
    matchLabels:
      name: test
  template:
    metadata:
      labels:
        name: test
    spec:
      containers:
      - name: test
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: danialnabiyan1382/csi:v1.0.0.2
        securityContext:
          privileged: true